### ISSUE TITLE
Continuous "Server disconnected" error

### ISSUE THREAD

**Issue by gamberoillecito** [Lenochxd/WebDeck#22]
**Describe the bug**
Right after installation webDeck is almost unusable since both the webpage on the phone and the webpage on the PC where webdeck is running show "Server disconnected"

**To Reproduce**
1. Start the executable on windows
2. Click on "Open config"
3. Wait a couple of seconds
4. The message appears

Refreshing the page seems to make the issue stop temporarily but after a couple of seconds the same message reappears

**Screenshots**

![immagine](https://github.com/Lenochxd/WebDeck/assets/42670032/9e26d4ae-520a-4410-9d0a-b4adb8ad503e)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro version 10.0.22631
 - Browser Firefox version 127.0

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 15
 - Browser: Firefox version 127.0.1

**Additional context**

The issue is the same on both the PC and the smartphone

**Comment by Lenochxd** [comment]
Hey, thank you for reporting a bug.
Are you still able to click on a button even on this screen?

**Comment by gamberoillecito** [comment]
@Lenochxd yes I am, for example I can reload the page with the button instead of having to use the F5 key or the browser

**Comment by Lenochxd** [comment]
Yes this is normal, the reload button does not need the server to work. Do the other buttons work? like the 'enable screen saver' button for example.

Also, can you show me a quick screenshot of the browser console? You can see it by pressing F12, it should appear at the bottom. If a menu appears but no console, press your ESC key.

Thanks :)

**Comment by gamberoillecito** [comment]
I tested everything on my PC to exclude network errors, I can confirm that everything seem to work even with the error message on top. These are the logs:

[console-export-2024-6-22_12-37-31.txt](https://github.com/user-attachments/files/15936214/console-export-2024-6-22_12-37-31.txt)

Thank you for your help

**Comment by Lenochxd** [comment]
That's what I thought, there is an error with the computer usage buttons, and you seem to have an NVIDIA graphics card as the GPU percentage is displayed.
I will try to fix the error, you can try changing the "GPU usage method" setting in the meantime.

**Comment by gamberoillecito** [comment]
Changing to "none" seems to have solved the issue. I don't really care about GPU stats so that's not an issue right now. Thank you very much. I'll keep testing the app because it seems very functional 😄

**Comment by Lenochxd** [comment]
Should be fixed on [1.8.6](https://github.com/Lenochxd/WebDeck/releases/tag/v1.8.6) (ade4ea8e19523f9e99d79020e7f565b42094d776)

**Comment by hannesdelbeke** [comment]
i believe i still get this error, when testing on my desktop in chrome. (the same desktop is also hosting the webdeck.exe)
i also have a NVIDEA card

**Comment by hannesdelbeke** [comment]
i can confirm that changing gpu to None in settings fixes this issue. it was on NVIDEA by default.
would it be worth setting it to None by default?

**Comment by Lenochxd** [comment]
The issue has been fixed and will be fixed in the next release
